import { FinanceReportTableColumns } from "../finance-report-page/types";

export enum FinanceReportDateType {
  AsAt = "AsAt",
  StartAndEnd = "StartAndEnd",
}

export enum FinanceReportTypes {
  BillDetailsReport = "Bill Details Report",
  PaymentsMadeReport = "Payments Made Report",
  PaymentsReceivedReport = "Payments Received Report",
  ExpensesReport = "Expenses Report",
  ExpensesByCategoryReport = "Expenses By Category Report",
  AgingSummaryReport = "Aging Summary Report",
  AgingDetailsReport = "Aging Details Report",
  AccountTransactionsReport = "Account Transactions Report",
  ActivityLogReport = "Activity Log Report",
  CashAdvanceReport = "Cash Advance Report",
  ReconciliationSummary = "Reconciliation Summary",
  SalesByCustomerReport = "Sales By Customer",
  SalesBySalespersonReport = "Sales By Salesperson",
  SalesByItemReport = "Sales By Item",
  CreditNoteDetails = "Credit Note Details",
  VendorCreditNoteDetails = "Vendor Credit Note Details",
  PettyCashReport = "Petty Cash Report",
  InvoiceDetailsReport = "Invoice Details Report",
  BillAgingDetailsReport = "Bill Aging Details Report",
  BillAgingSummaryReport = "Bill Aging Summary Report",
  InvoiceAgingDetailsReport = "Invoice Aging Details Report",
  InvoiceAgingSummaryReport = "Invoice Aging Summary Report",
  AccountSummary = "Account Summary",
  PurchasesByVendorReport = "Purchases By Vendor Report",
  PurchasesByItemReport = "Purchases By Item Report",
  CustomerBalancesReport = "Customer Balances Report",
  VendorBalancesReport = "Vendor Balances Report",
  CreditRefundReport = "Credit Refund Report",
  AssetScheduleReport = "Assets Schedule Report",
  AssetRegisterReport = "Asset Register Report",
  GeneralLedgerReport = "General Ledger Report",
  ProfitLossReport = "Profit or Loss Report",
  TrialBalanceReport = "Trial Balance Report",
  BalanceSheetReport = "Balance Sheet Report",
}

export enum FinanceReportNames {
  BillDetailsReport = "BillDetailsReport",
  PaymentsMadeReport = "PaymentsMadeReport",
  PaymentsReceivedReport = "PaymentsReceivedReport",
  ExpensesReport = "ExpensesReport",
  ExpensesByCategoryReport = "ExpensesByCategory",
  AgingSummaryReport = "AgingSummaryReport",
  AgingDetailsReport = "AgingDetailsReport",
  AccountTransactionsReport = "AccountTransactionsReport",
  ActivityLogReport = "ActivityLogReport",
  CashAdvanceReport = "CashAdvanceReport",
  ReconciliationSummary = "ReconciliationSummary",
  SalesByCustomerReport = "SalesByCustomer",
  SalesBySalespersonReport = "SalesBySalesperson",
  SalesByItemReport = "SalesByItem",
  CreditNoteDetails = "CreditNoteDetails",
  VendorCreditNoteDetails = "VendorCreditNoteDetails",
  PettyCashReport = "PettyCashReport",
  InvoiceDetailsReport = "InvoiceDetailsReport",
  BillAgingDetailsReport = "BillAgingDetailsReport",
  BillAgingSummaryReport = "BillAgingSummaryReport",
  InvoiceAgingDetailsReport = "InvoiceAgingDetailsReport",
  InvoiceAgingSummaryReport = "InvoiceAgingSummaryReport",
  AccountSummary = "AccountSummary",
  PurchasesByVendorReport = "PurchasesByVendorReport",
  PurchasesByItemReport = "PurchasesByItemReport",
  CustomerBalancesReport = "CustomerBalancesReport",
  VendorBalancesReport = "VendorBalancesReport",
  CreditRefundReport = "CreditRefundReport",
  AssetScheduleReport = "AssetScheduleReport",
  AssetRegisterReport = "AssetRegisterReport",
  GeneralLedgerReport = "GeneralLedgerReport",
  ProfitLossReport = "ProfitAndLossReport",
  TrialBalanceReport = "TrialBalanceReport",
  BalanceSheetReport = "BalanceSheetReport",
}

export const FinanceReportTableCols: FinanceReportTableColumns = {
  CreditRefundReport: [
    { name: "Code", property: "creditCode", class: "code" },
    { name: "Approved By", property: "approvedBy" },
    { name: "Refunded To", property: "refundedTo" },
    { name: "Date", property: "refundDate", type: "date", alignment: "center" },
    {
      name: "Amount",
      property: "refundAmount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  BillDetailsReport: [
    { name: "Code", property: "billCode", class: "code" },
    { name: "Vendor", property: "vendorName" },
    {
      name: "Bill Date",
      property: "billDate",
      type: "date",
      alignment: "center",
    },
    {
      name: "Bill Due Date",
      property: "dueDate",
      type: "date",
      alignment: "center",
    },
    { name: "Status", property: "status" },
    {
      name: "Amount",
      property: "billAmount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  VendorBalancesReport: [
    { name: "Name", property: "vendorName" },
    {
      name: "Available Credits",
      property: "availableCredits",
      alignment: "right",
      type: "number",
    },
    {
      name: "Balance",
      property: "balance",
      alignment: "right",
      type: "number",
    },
    {
      name: "Bill Balance",
      property: "billBalance",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  CustomerBalancesReport: [
    { name: "Name", property: "customerName" },
    {
      name: "Available Credits",
      property: "availableCredits",
      alignment: "right",
      type: "number",
    },
    {
      name: "Balance",
      property: "balance",
      alignment: "right",
      type: "number",
    },
    {
      name: "Invoice Balance",
      property: "invoiceBalance",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  PurchasesByItemReport: [
    { name: "Name", property: "name" },
    { name: "Quantity", property: "quantityBought", alignment: "center" },
    { name: "Item Type", property: "itemType" },
    {
      name: "Average Price",
      property: "averagePrice",
      alignment: "right",
      type: "number",
    },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  PurchasesByVendorReport: [
    { name: "Name", property: "name" },
    { name: "Bills Count", property: "billsCount", alignment: "center" },
    {
      name: "Purchases",
      property: "purchases",
      alignment: "right",
      type: "number",
    },
    {
      name: "Purchases With Tax",
      property: "purchasesWithTax",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  CashAdvanceReport: [
    { name: "Code", property: "code", class: "code" },
    { name: "Date", property: "createdAt", type: "date", alignment: "center" },
    {
      name: "Receipt Date",
      property: "expectedCashAdvanceReceiptDate",
      type: "date",
      alignment: "center",
    },
    { name: "Treated By", property: "treatedBy" },
    { name: "Staff Account", property: "staffAccount" },
    { name: "Paid Through Account", property: "paidThroughAccount" },
    { name: "Reference", property: "paidThroughAccountReference" },
    { name: "Branch", property: "branch" },
    { name: "Status", property: "status" },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
  ],
  ReconciliationSummary: [
    { name: "Code", property: "cashAdvanceCode", class: "code" },
    {
      name: "Created At",
      property: "createdAt",
      type: "date",
      alignment: "center",
    },
    {
      name: "Transaction Date",
      property: "transactionDate",
      type: "date",
      alignment: "center",
    },
    { name: "Branch", property: "branch" },
    { name: "Reconciled By", property: "reconciledBy" },
    {
      name: "Reconciled Amount",
      property: "reconciledAmount",
      alignment: "right",
      type: "number",
    },
  ],
  AccountSummary: [
    { name: "Name", property: "name" },
    { name: "Account Type", property: "accountType" },
    {
      name: "Credit Sum",
      property: "creditSum",
      alignment: "right",
      type: "number",
    },
    {
      name: "Debit Sum",
      property: "debitSum",
      alignment: "right",
      type: "number",
    },
  ],
  BillAgingDetailsReport: [
    { name: "Date", property: "date", type: "date", alignment: "center" },
    {
      name: "Due Date",
      property: "dueDate",
      type: "date",
      alignment: "center",
    },
    { name: "Code", property: "code", class: "code" },
    { name: "Name", property: "name" },
    { name: "Age", property: "age", alignment: "center" },
    {
      name: "Balance Due",
      property: "balanceDue",
      alignment: "right",
      type: "number",
    },
    { name: "Payment Status", property: "paymentStatus" },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  InvoiceAgingDetailsReport: [
    { name: "Date", property: "date", type: "date", alignment: "center" },
    {
      name: "Due Date",
      property: "dueDate",
      type: "date",
      alignment: "center",
    },
    { name: "Code", property: "code", class: "code" },
    { name: "Name", property: "name" },
    { name: "Age", property: "age", alignment: "center" },
    { name: "Payment Status", property: "paymentStatus" },
    {
      name: "Branch",
      property: "branch",
    },
    {
      name: "Balance Due",
      property: "balanceDue",
      alignment: "right",
      type: "number",
    },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
  ],
  InvoiceDetailsReport: [
    { name: "Code", property: "invoiceCode", class: "code" },
    { name: "Customer Name", property: "customerName" },
    {
      name: "Invoice Date",
      property: "invoiceDate",
      type: "date",
      alignment: "center",
    },
    {
      name: "Invoice Due Date",
      property: "invoiceDueDate",
      type: "date",
      alignment: "center",
    },
    { name: "Payment Status", property: "paymentStatus" },
    { name: "Status", property: "status" },
    {
      name: "Branch",
      property: "branch",
    },
    {
      name: "Balance",
      property: "balance",
      alignment: "right",
      type: "number",
    },
    {
      name: "Total",
      property: "total",
      alignment: "right",
      type: "number",
    },
  ],
  InvoiceAgingSummaryReport: [
    { name: "Name", property: "name" },
    {
      name: "Current",
      property: "current",

      alignment: "right",
      type: "number",
    },
    {
      name: "1 - 15 Days",
      property: "_1to15_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "16 - 30 Days",
      property: "_16to30_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "31 - 45 Days",
      property: "_31to45_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "Above 45 Days",
      property: "_Above45_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "Total",
      property: "total",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  BillAgingSummaryReport: [
    { name: "Name", property: "name" },
    {
      name: "Current",
      property: "current",
      alignment: "right",
      type: "number",
    },
    {
      name: "1 - 15 Days",
      property: "_1to15_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "16 - 30 Days",
      property: "_16to30_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "31 - 45 Days",
      property: "_31to45_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "Above 45 Days",
      property: "_Above45_Days",
      alignment: "right",
      type: "number",
    },
    {
      name: "Total",
      property: "total",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  VendorCreditNoteDetails: [
    { name: "Code", property: "vendorCreditNoteCode", class: "code" },
    { name: "Vendor Name", property: "vendorName" },
    {
      name: "Credit Date",
      property: "creditDate",
      type: "date",
      alignment: "center",
    },
    { name: "Status", property: "status" },
    {
      name: "Balance Amount",
      property: "balanceAmount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Amount",
      property: "vendorCreditNoteAmount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  PettyCashReport: [
    { name: "Code", property: "transactionCode", class: "code" },
    { name: "Recipient", property: "recipientInformation" },
    {
      name: "Date",
      property: "transactionDate",
      type: "date",
      alignment: "center",
    },
    { name: "Expense Account", property: "expenseAccount" },
    { name: "Debit Account", property: "debitAccount" },
    { name: "Status", property: "status" },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  ActivityLogReport: [
    { name: "Description", property: "activityDescription" },
    {
      name: "Date",
      property: "activityDate",
      type: "date",
      alignment: "center",
    },
  ],
  ExpensesByCategory: [
    { name: "Category", property: "category" },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Amount With Tax",
      property: "amountWithTax",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  ExpensesReport: [
    { name: "Vendor Name", property: "vendorName" },
    { name: "Customer Name", property: "customerName" },
    { name: "Date", property: "date", type: "date", alignment: "center" },
    { name: "Status", property: "status" },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Amount With Tax",
      property: "amountWithTax",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  CreditNoteDetails: [
    { name: "Code", property: "creditNoteCode", class: "code" },
    { name: "Customer Name", property: "customerName" },
    {
      name: "Credit Date",
      property: "creditDate",
      type: "date",
      alignment: "center",
    },
    { name: "Status", property: "status" },
    {
      name: "Credit Note Amount",
      property: "creditNoteAmount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Balance Amount",
      property: "balanceAmount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  AccountTransactionsReport: [
    { name: "Code", property: "label", class: "code" },
    { name: "Branch", property: "branch" },
    { name: "Account", property: "account" },
    {
      name: "Transaction Date",
      property: "transactionDate",
      type: "date",
      alignment: "center",
    },
    { name: "Reference", property: "reference" },
    { name: "Status", property: "status" },
    {
      name: "Credit Amount",
      property: "creditAmount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Debit Amount",
      property: "debitAmount",
      alignment: "right",
      type: "number",
    },
  ],
  PaymentsMadeReport: [
    { name: "Code", property: "billCode", class: "code" },
    { name: "Vendor", property: "vendor" },
    {
      name: "Payment Date",
      property: "paymentDate",
      type: "date",
      alignment: "center",
    },
    { name: "Deposit To", property: "depositTo" },
    { name: "Payment Mode", property: "paymentMode" },
    { name: "Reference", property: "reference" },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  PaymentsReceivedReport: [
    { name: "Code", property: "invoiceCode", class: "code" },
    { name: "Customer", property: "customer" },
    {
      name: "Payment Date",
      property: "paymentDate",
      type: "date",
      alignment: "center",
    },
    { name: "Account", property: "depositTo" },
    { name: "Payment Mode", property: "paymentMode" },
    { name: "Reference", property: "reference" },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  SalesBySalesperson: [
    { name: "Salesperson", property: "salePersonName" },
    {
      name: "Credit Note Count",
      property: "creditNoteCount",
      alignment: "center",
    },
    {
      name: "Credit Note Sales",
      property: "creditNoteSales",
      alignment: "right",
    },
    {
      name: "Credit Note Sales With Tax",
      property: "creditNoteSalesWithTax",
      alignment: "center",
      type: "number",
    },
    { name: "Invoice Count", property: "invoiceCount", alignment: "center" },
    {
      name: "Sales",
      property: "sales",
      alignment: "right",
      type: "number",
    },
    {
      name: "Sales With Tax",
      property: "salesWithTax",
      alignment: "right",
      type: "number",
    },
    {
      name: "Total Sales",
      property: "totalSales",
      alignment: "right",
      type: "number",
    },
    {
      name: "Total Sales With Tax",
      property: "totalSalesWithTax",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  SalesByCustomer: [
    { name: "Name", property: "name" },
    { name: "Invoice Count", property: "invoiceCount", alignment: "center" },
    {
      name: "Sales",
      property: "sales",
      alignment: "right",
      type: "number",
    },
    {
      name: "Sales With Tax",
      property: "salesWithTax",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  SalesByItem: [
    { name: "Name", property: "name" },
    { name: "Quantity Sold", property: "quantitySold", alignment: "center" },
    { name: "Item Type", property: "itemType" },
    {
      name: "Average Price",
      property: "averagePrice",
      alignment: "right",
      type: "number",
    },
    {
      name: "Amount",
      property: "amount",
      alignment: "right",
      type: "number",
    },
    {
      name: "Branch",
      property: "branch",
    },
  ],
  AssetSchedule: [
    { name: "Asset Sub-class Name", property: "assetSubClassName" },
    {
      name: "Accum. Dep. Period Opening Balance",
      property: "accumDepPeriodOpeningBalance",
      type: "number",
      alignment: "right",
    },
    {
      name: "Accum. Dep. Period Closing Balance",
      property: "accumDepPeriodClosingBalance",
      type: "number",
      alignment: "right",
    },
    {
      name: "Accum. Dep. Disposals In Period",
      property: "accumDepDisposalsInPeriod",
      type: "number",
      alignment: "right",
    },
    {
      name: "Accum. Depreciation In Period",
      property: "accumDepreciationInPeriod",
      type: "number",
      alignment: "right",
    },
    {
      name: "Cost Period Opening Balance",
      property: "costPeriodOpeningBalance",
      type: "number",
      alignment: "right",
    },
    {
      name: "Cost Period Closing Balance",
      property: "costPeriodClosingBalance",
      type: "number",
      alignment: "right",
    },
    {
      name: "Cost Disposals In Period",
      property: "costDisposalsInPeriod",
      type: "number",
      alignment: "right",
    },
    {
      name: "Cost Additions In Period",
      property: "costAdditionsInPeriod",
      type: "number",
      alignment: "right",
    },
    {
      name: "Period Net Book Value",
      property: "periodNetBookValue",
      type: "number",
      alignment: "right",
    },
    {
      name: "Branch",
      property: "branchName",
    },
  ],
  AssetRegister: [
    {
      name: "Asset Code",
      property: "assetCode",
      type: "code",
    },
    {
      name: "Branch",
      property: "branchName",
    },
    { name: "Asset Name", property: "assetName" },
    { name: "Asset Description", property: "descriptionOfAsset" },
    {
      name: "Purchase Date",
      property: "dateOfPurchaseOrAcquisition",
      type: "date",
    },
    { name: "Class", property: "assetClass" },
    {
      name: "Depreciation Rate (%)",
      property: "depreciationRate",
      alignment: "center",
    },
    {
      name: "Depreciation Method",
      property: "depreciationMethod",
    },
    {
      name: "Purchase Price",
      property: "purchasePrice",
      type: "number",
    },
    {
      name: "Total Cost",
      property: "totalCost",
      type: "number",
    },
    {
      name: "Total Depreciation",
      property: "totalDepreciation",
      type: "number",
    },
    {
      name: "Net Book Value",
      property: "netBookValue",
      type: "number",
    },
    {
      name: "Status",
      property: "status",
      alignment: "center",
    },
    { name: "Asset Subclass", property: "assetSubClassName" },
    {
      name: "Residual Value",
      property: "residualValue",
      type: "number",
    },
    {
      name: "Depreciation Start Date",
      property: "depreciationStartDate",
      type: "date",
    },
    {
      name: "Effective Life in Years",
      property: "effectiveLifeInYears",
      alignment: "center",
    },
    { name: "Created By", property: "createdBy" },
    {
      name: "Activation Date",
      property: "assetActivationDate",
      type: "date",
    },
    {
      name: "Assigned Employee",
      property: "assignedEmployee",
    },
    {
      name: "Date Disposed",
      property: "dateDisposed",
      type: "date",
    },
  ],
  GeneralLedger: [
    { name: "Account Name", property: "name" },
    {
      name: "Account Code",
      property: "reference",
    },
    { name: "Debit", property: "debitSum", type: "number", alignment: "right" },
    {
      name: "Credit",
      property: "creditSum",
      type: "number",
      alignment: "right",
    },
    {
      name: "Balance",
      property: "balance",
      type: "number",
      alignment: "right",
    },
  ],
};

export const FinanceReportTableSubCols: FinanceReportTableColumns = {
  AccountSummary: [
    { name: "Name", property: "name" },
    { name: "AccountId", property: "accountId" },
    { name: "Credit Sum", property: "creditSum", alignment: "right" },
    { name: "Debit Sum", property: "debitSum", alignment: "right" },
  ],
};

export const financeReportRowHeaders = [
  { name: "Current", property: "current" },
  { name: "1 - 15 Days", property: "_1to15_Days" },
  { name: "16 - 30 Days", property: "_16to30_Days" },
  { name: "31 - 45 Days", property: "_31to45_Days" },
  { name: "Above 45 Days", property: "_Above45_Days" },
];
